### ISSUE TITLE
Diagnostics vignette download file path

### ISSUE THREAD

**Issue by KevinSee** [mackerman44/telemetyr#22]
The diagnostics vignette relies on downloading some diagnostic data using a "download_path" input. However, this input is different for different users, and wouldn't work at all for folks without access to the 2018-2019 data. 

Consider reading in the volt-temperature data for 2018-2019 and saving it as a data object, or internal data object in the package.

**Comment by mackerman44** [comment]
Ah, I see I forgot to put eval = FALSE on the data-path chunk. Is that what you mean? Because later I do just load the compressed.rda from 2018-2019 that is saved in the package and use that moving forward.

I see your point on saving the 2018-2019 volt-temperature data. Does it make sense to save that in the data/prepped/2018_2019/ folder? Or at some point do we need to start saving some data in the root data/ folder to use as examples to be loaded with the package.

**Comment by KevinSee** [comment]
It was the chunk reading in the volt-temperature data that was causing me trouble. I think, if we're going to share this package with WDFW, we may want to pick a year and save some of that data in the data/ folder. That way we ensure that even if a user doesn't clone the repo, but only installs the package, the vignettes still work for them. We'd need to do the same with one year of the compressed data as well, or maybe a subset of it.

**Comment by mackerman44** [comment]
Sounds good to me. I'm thinking we pick a day soon to roll this out to Nick to start testing and maybe one of us can spend a few hours cleaning the repo for that including saving appropriate data for loading, data and function documentation, build testing, etc?

**Comment by KevinSee** [comment]
I think Mike has fixed all of this by creating example datasets that are referenced in the vignettes. The scripts to create all the examples are in the data-raw folder, and they all point to the NAS with "S:/". For Kevin, I need to replace "S:/" with "~/../../Volumes/ABS/" and then they work for me too.
