### ISSUE TITLE
Missing package

### ISSUE THREAD

**Issue by port5518** [mackerman44/telemetyr#33]
The package ps is missing and I needed to load it manually.

**Comment by mackerman44** [comment]
Thanks for catching that, Nick. I just updated the DESCRIPTION file to include all currently known imports. Crossing my fingers it remedies the above, but let me know if you see any similar errors.

Kevin - I just discovered the use_package() function in usethis:: to easily add a package to your DESCRIPTION file. Also, in doing some digging, I found it bad practice to use tidyverse() as an Import since it's a "meta package", and instead include the individual packages as Imports. Hadley even provides a nice little description if you use usethis::use_package("tidyverse").
