### ISSUE TITLE
T & Z in start and end times in compressed .csv files

### ISSUE THREAD

**Issue by mackerman44** [mackerman44/telemetyr#35]
Nick noticed that when we write a .csv of the compressed data the "start" and "end" times contain a T and Z within the times. Presumably this stood for timezone and is an issue when writing data to .csv or opening in Excel. Stupid f'ing Excel! I verified this was the case in all 3 compressed datasets in S:/Nick/telemetry/raw/. Maybe dig in a little further?

I have not confirmed whether that's also the case in the raw .csv files.

**Comment by KevinSee** [comment]
Ack. I'm guessing this is an excel thing, not knowing how to format data-time data. I'll come up with a fix, and probably save things as a csv, if someone wants to open it up and scroll through, as well as an .rda object that avoids all the Excel shenanigans.

**Comment by KevinSee** [comment]
I re-read all the raw text files, and saved a raw_df and compress_df, as well as a cap_hist_list, for each year as .rda objects on the NAS, bypassing csv files. If someone **_needs_** csv files in order to scroll through and examine it that way as part of a QA/QC process, please let us know, and we'll come up with a solution. The csv files were quite large however, and if they're not needed I won't bother.
